class _xx_quickclot { name = "ACE_quikclot"; count = 5; };
class _xx_packBandage { name = "ACE_packingBandage"; count = 5; };
class _xx_tourniquet { name = "ACE_tourniquet"; count = 2; };
class _xx_splint { name = "ACE_splint"; count = 2; };
class _xx_epi { name = "ACE_epinephrine"; count = 1; };
class _xx_aden { name = "ACE_adenosine"; count = 1; };
class _xx_morph { name = "ACE_morphine"; count = 4; };
class _xx_saline500 { name = "ACE_salineIV_500"; count = 2; };
class _xx_blood { name = "ACE_bloodIV"; count = 1; };
class _xx_bodybag { name = "ACE_bodyBag"; count = 1; };
class _xx_earplug { name = "ACE_EarPlugs"; count = 1; };
class _xx_mapt { name = "ACE_MapTools"; count = 1; };
class _xx_m26 { name = "ACE_M26_Clacker"; count = 1; };
class _xx_strobe{ name = "ACE_IR_Strobe_Item"; count = 1; };
class _xx_cabletie{ name = "ACE_CableTie"; count = 1; };
class _xx_huntir { name = "ACE_HuntIR_monitor"; count = 1; };
class _xx_waterbot { name = "ACE_WaterBottle"; count = 1; };
class _xx_canteen { name = "ACE_Canteen"; count = 1; };
class _xx_mdagr { name = "ACE_microDAGR"; count = 1; };