weapons[] = {
    "MSF_MXGL_White",
    #include "\z\msf\addons\units\u\vehicles\base\Base_Weap_HgunBino.inc"
};
magazines[] = {
    #include "\z\msf\addons\units\u\vehicles\base\Base_Mags.inc"
    #include "\z\msf\addons\units\u\vehicles\base\Base_Mags_MX.inc"
    #include "\z\msf\addons\units\u\vehicles\base\Base_Mags_Hgun.inc"
    "1Rnd_SmokeGreen_Grenade_shell", "1Rnd_SmokeGreen_Grenade_shell", "1Rnd_SmokeGreen_Grenade_shell",
    "1Rnd_SmokeGreen_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell",
    "UGL_FlareGreen_F", "UGL_FlareGreen_F", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", 
    "1Rnd_HE_Grenade_shell", "ACE_HuntIR_M203", "ACE_HuntIR_M203", "ACE_HuntIR_M203", "ACE_HuntIR_M203", "ACE_HuntIR_M203"
};
respawnWeapons[] = {
    "MSF_MXGL_White",
    #include "\z\msf\addons\units\u\vehicles\base\Base_Weap_HgunBino.inc"
};
respawnMagazines[] = {
    #include "\z\msf\addons\units\u\vehicles\base\Base_Mags.inc"
    #include "\z\msf\addons\units\u\vehicles\base\Base_Mags_MX.inc"
    #include "\z\msf\addons\units\u\vehicles\base\Base_Mags_Hgun.inc"
    "1Rnd_SmokeGreen_Grenade_shell", "1Rnd_SmokeGreen_Grenade_shell", "1Rnd_SmokeGreen_Grenade_shell",
    "1Rnd_SmokeGreen_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell",
    "UGL_FlareGreen_F", "UGL_FlareGreen_F", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", 
    "1Rnd_HE_Grenade_shell", "ACE_HuntIR_M203", "ACE_HuntIR_M203", "ACE_HuntIR_M203", "ACE_HuntIR_M203", "ACE_HuntIR_M203"
};
