weapons[] = {
    "MSF_MX_W_u",
    #include "\z\msf\addons\units\u\vehicles\base\Base_Weap_HgunBino.inc"
};
magazines[] = {
    #include "\z\msf\addons\units\u\vehicles\base\Base_Mags.inc"
    #include "\z\msf\addons\units\u\vehicles\base\Base_Mags_MX.inc"
    #include "\z\msf\addons\units\u\vehicles\base\Base_Mags_Hgun.inc"
};
respawnWeapons[] = {
    "MSF_MX_W_u",
    #include "\z\msf\addons\units\u\vehicles\base\Base_Weap_HgunBino.inc"
};
respawnMagazines[] = {
    #include "\z\msf\addons\units\u\vehicles\base\Base_Mags.inc"
    #include "\z\msf\addons\units\u\vehicles\base\Base_Mags_MX.inc"
    #include "\z\msf\addons\units\u\vehicles\base\Base_Mags_Hgun.inc"
};
