class arifle_MX_Black_F;
class arifle_MX_GL_F;
class arifle_MX_F;
class arifle_MXC_Black_F;
class arifle_MXC_F;
class arifle_MX_GL_Black_F;
class arifle_MXM_Black_F;
class arifle_MXM_F;
class LMG_03_F;
class launch_B_Titan_F;
class srifle_DMR_02_sniper_F;
class srifle_DMR_02_camo_F;

#include "weapons\blufor\MSF_M249.hpp"
#include "weapons\blufor\MSF_Sniper.hpp"
#include "weapons\blufor\MSF_Sniper_T.hpp"
#include "weapons\blufor\MSF_Sniper_W.hpp"
#include "weapons\blufor\MSF_MX.hpp"
#include "weapons\blufor\MSF_MX_T.hpp"
#include "weapons\blufor\MSF_MXC.hpp"
#include "weapons\blufor\MSF_MXC_T.hpp"
#include "weapons\blufor\MSF_MXM.hpp"
#include "weapons\blufor\MSF_MX_3GL.hpp"
#include "weapons\blufor\MSF_MXGL_B.hpp"
#include "weapons\blufor\MSF_MXGL_T.hpp"
#include "weapons\blufor\MSF_MX_B.hpp"
#include "weapons\blufor\MSF_MXC_B.hpp"
#include "weapons\blufor\MSF_MXM_B.hpp"
#include "weapons\blufor\Weap_w.hpp"
#include "weapons\blufor\MSF_MXC_W.hpp"
#include "weapons\blufor\MSF_MXGL_W.hpp"
#include "weapons\blufor\launcher\MSF_Launch_B_Titan.hpp"

#include "weapons\opfor\MSF_ARC_SPAR.hpp"
#include "weapons\opfor\MSF_ARC_SPAR_MG.hpp"
#include "weapons\opfor\MSF_ARC_SPAR_GL.hpp"
#include "weapons\opfor\MSF_ARC_DMR.hpp"
