#include "weapons\MSF_MAR10.hpp"
#include "weapons\MSF_MXSW_W.hpp"
#include "weapons\MSF_MXGL_White.hpp"
#include "weapons\MSF_MMG_W.hpp"
#include "weapons\MSF_MXM_W.hpp"
#include "weapons\MSF_MXC_W.hpp"

#include "weapons\blufor\MSF_M249.hpp"
#include "weapons\blufor\MSF_MX.hpp"
#include "weapons\blufor\MSF_MX_3GL.hpp"
#include "weapons\blufor\MSF_MXC.hpp"
#include "weapons\blufor\MSF_MXM.hpp"
#include "weapons\blufor\MSF_MXGL_B.hpp"
#include "weapons\blufor\MSF_MX_B.hpp"
#include "weapons\blufor\MSF_MXC_B.hpp"
#include "weapons\blufor\MSF_MXM_B.hpp"

#include "weapons\opfor\MSF_ARC_SPAR.hpp"
#include "weapons\opfor\MSF_ARC_SPAR_MG.hpp"
#include "weapons\opfor\MSF_ARC_SPAR_GL.hpp"
#include "weapons\opfor\MSF_ARC_DMR.hpp"