weapons[] = {
    "MSF_MX_3GL",
    #include "../../base/Base_Weap_HgunBino.inc"
};
magazines[] = {
    #include "../../base/Base_Mags.inc"
    #include "../../base/Base_Mags_MX.inc"
    #include "../../base/Base_Mags_Hgun.inc"
    "1Rnd_SmokeGreen_Grenade_shell", "1Rnd_SmokeGreen_Grenade_shell", "1Rnd_SmokeGreen_Grenade_shell",
    "1Rnd_SmokeGreen_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell",
    "UGL_FlareGreen_F", "UGL_FlareGreen_F", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", 
    "1Rnd_HE_Grenade_shell", "ACE_HuntIR_M203", "ACE_HuntIR_M203", "ACE_HuntIR_M203", "ACE_HuntIR_M203", "ACE_HuntIR_M203"
};
respawnWeapons[] = {
    "MSF_MX_3GL",
    #include "../../base/Base_Weap_HgunBino.inc"
};
respawnMagazines[] = {
    #include "../../base/Base_Mags.inc"
    #include "../../base/Base_Mags_MX.inc"
    #include "../../base/Base_Mags_Hgun.inc"
    "1Rnd_SmokeGreen_Grenade_shell", "1Rnd_SmokeGreen_Grenade_shell", "1Rnd_SmokeGreen_Grenade_shell",
    "1Rnd_SmokeGreen_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell",
    "UGL_FlareGreen_F", "UGL_FlareGreen_F", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", 
    "1Rnd_HE_Grenade_shell", "ACE_HuntIR_M203", "ACE_HuntIR_M203", "ACE_HuntIR_M203", "ACE_HuntIR_M203", "ACE_HuntIR_M203"
};