weapons[] = {
    "MSF_M249",
    #include "../../base/Base_Weap_HgunBino.inc"
};
magazines[] = {
    #include "../../base/Base_Mags.inc"
    #include "../../base/Base_Mags_Hgun.inc"
    "200Rnd_556x45_Box_Tracer_Red_F", "200Rnd_556x45_Box_Tracer_Red_F", "200Rnd_556x45_Box_Tracer_Red_F",
    "200Rnd_556x45_Box_Tracer_Red_F"
};
respawnWeapons[] = {
    "MSF_M249",
    #include "../../base/Base_Weap_HgunBino.inc"
};
respawnMagazines[] = {
    #include "../../base/Base_Mags.inc"
    #include "../../base/Base_Mags_Hgun.inc"
    "200Rnd_556x45_Box_Tracer_Red_F", "200Rnd_556x45_Box_Tracer_Red_F", "200Rnd_556x45_Box_Tracer_Red_F",
    "200Rnd_556x45_Box_Tracer_Red_F"
};