weapons[] = {
    "MSF_MX",
    #include "../../base/Base_Weap_HgunBino.inc"
};
magazines[] = {
    #include "../../base/Base_Mags.inc"
    #include "../../base/Base_Mags_MX.inc"
    #include "../../base/Base_Mags_Hgun.inc"
};
respawnWeapons[] = {
    "MSF_MX",
    #include "../../base/Base_Weap_HgunBino.inc"
};
respawnMagazines[] = {
    #include "../../base/Base_Mags.inc"
    #include "../../base/Base_Mags_MX.inc"
    #include "../../base/Base_Mags_Hgun.inc"
};
